---@type string, Spotlights
local _, Private = ...

local L = Private.L

L.SlashCommands.Usage = "Befehle:"
L.SlashCommands.Help = "Listet alle Befehle auf"
L.SlashCommands.Mover = "Entsperrt das Raster zum Verschieben"
L.SlashCommands.Recenter = "Setzt das Raster in die Bildschirmmitte zurück"
L.SlashCommands.Add = "Hebt ein Schlachtzugsmitglied namentlich hervor"
L.SlashCommands.List = "Listet die konfigurierten Plätze auf"
L.SlashCommands.Rescan = "Erzwingt einen erneuten Abgleich aller belegten Plätze mit der Gruppe"
L.SlashCommands.Options = "Öffnet das Einstellungsfenster"
L.SlashCommands.OptionsPreview = "Öffnet das überarbeitete Einstellungsfenster, das noch entsteht"

L.Migration.FromTheFuture =
"gespeicherte Einstellungen haben Version %d, aber dieser Build versteht %d – sie wurden unangetastet gelassen statt herabgestuft"

L.Registry.NotLoaded = "gespeicherte Einstellungen wurden noch nicht geladen"
L.Registry.AddUsage = "Verwendung: /spotlights add <Name>"
L.Registry.Unknown = "kein Schlachtzugsmitglied entspricht '%s'"
L.Registry.IdentitySecret =
"'%s' kann nicht abgeglichen werden – %d Schlachtzugsmitglied(er) haben hier geheime Identitäten"
L.Registry.NotInRoster =
"dieser Spieler ist nicht im Schlachtzug, daher kann sein Name nicht zuverlässig abgeglichen werden"
L.Registry.Duplicate = "%s belegt bereits Platz %d"
L.Registry.NoSuchSlot = "es gibt keinen Platz %d"
L.Registry.Assigned = "Platz %d hebt %s hervor"
L.Registry.Deferred = "im Kampf – die Rahmen ziehen nach, sobald er endet"
L.Registry.Rescanned = "%d Platz/Plätze erneut mit der Gruppe abgeglichen"
L.Registry.Empty = "keine Plätze konfiguriert – versuche /spotlights add <Name>"
L.Registry.ListHeader = "%d Platz/Plätze, %d Gruppenname(n) lesbar, %d geheim"
L.Registry.ListPlayer = "  %d. %s |cff808080%s|r"
L.Registry.ListBlank = "  %d. |cff808080(Platzhalter)|r"
L.Registry.Absent = "nicht im Schlachtzug"
L.Registry.Unresolved = "noch keine GUID"
L.Registry.ClearedOnLeave = "Schlachtzug verlassen – Gruppe wie konfiguriert geleert"

L.Layout.NotLoaded = "gespeicherte Einstellungen wurden noch nicht geladen"

L.Settings.Title = "Spotlights"
L.Settings.CombatRefused = "Einstellungen können im Kampf nicht geöffnet werden"
L.Settings.ClosedByCombat = "Einstellungen geschlossen: Kampf beginnt"
L.Settings.TabGeneral = "Allgemein"
L.Settings.TabAppearance = "Aussehen"
L.Settings.TabGrid = "Raster"
L.Settings.TabAuras = "Auren"
L.Settings.TabRoster = "Gruppe"
L.Settings.TabImportExport = "Import / Export"
L.Settings.ShowMinimapButton = "Minimap-Schaltfläche anzeigen"
L.Settings.ClickToOpenSettings = "Klicken, um die Einstellungen zu öffnen"
L.Settings.Import = "Importieren"
L.Settings.Export = "Exportieren"
L.Settings.ImportError = "Import fehlgeschlagen: %s"
L.Settings.ImportErrorPrefix = "die Zeichenkette beginnt nicht mit SPOTLIGHTS!"
L.Settings.ImportErrorDecode = "die Zeichenkette konnte nicht dekodiert werden"
L.Settings.ImportErrorPayload = "die dekodierten Daten sind keine Einstellungstabelle"
L.Settings.Copy = "Kopieren"
L.Settings.ToggleMover = "Entsperren / sperren"
L.Settings.Recenter = "Zurück zur Mitte"
L.Settings.PlacementHeading = "Platzierung"
L.Settings.InterfaceHeading = "Benutzeroberfläche"
L.Settings.UnlockFrames = "Rahmen zum Verschieben entsperren"
L.Settings.Scale = "Rahmenskalierung"
L.Settings.FrameStrata = "Rahmenebene"
L.Settings.SlashHint = "Gib |cffffd100/spotlights|r ein, um alle Befehle zu sehen."
L.Settings.Strata.BACKGROUND = "Hintergrund"
L.Settings.Strata.LOW = "Niedrig"
L.Settings.Strata.MEDIUM = "Mittel"
L.Settings.Strata.HIGH = "Hoch"
L.Settings.Strata.DIALOG = "Dialog"
L.Settings.Strata.FULLSCREEN = "Vollbild"
L.Settings.Strata.FULLSCREEN_DIALOG = "Vollbilddialog"
L.Settings.Strata.TOOLTIP = "Tooltip"
L.Settings.FrameHeading = "Rahmen"
L.Settings.Width = "Rahmenbreite"
L.Settings.Height = "Rahmenhöhe"
L.Settings.FrameAlpha = "Rahmentransparenz"
L.Settings.BarTexture = "Balkentextur"
L.Settings.TextureMissing = "%s (nicht geladen)"
L.Settings.ShowAbsorb = "Absorptionen anzeigen"
L.Settings.OutOfRangeAlpha = "Transparenz außer Reichweite"
L.Settings.DeadAlpha = "Transparenz bei Tod"
L.Settings.ColorClass = "Klassenfarbe"
L.Settings.ColorStatic = "Statische Farbe"
L.Settings.HealthColorMode = "Balkenfarbe"
L.Settings.HealthColor = "Statische Balkenfarbe"
L.Settings.HealthBgColor = "Hintergrundfarbe"
L.Settings.ResetFrame = "Rahmeneinstellungen zurücksetzen"
L.Settings.NameHeading = "Name"
L.Settings.NameColorMode = "Namensfarbe"
L.Settings.NameColor = "Statische Namensfarbe"
L.Settings.NameFont = "Namensschriftart"
L.Settings.NameFontSize = "Namensschriftgröße"
L.Settings.NameAnchor = "Namensanker"
L.Settings.NameOffsetX = "Namensversatz rechts"
L.Settings.NameOffsetY = "Namensversatz nach oben"
L.Settings.ResetName = "Namenseinstellungen zurücksetzen"
L.Settings.HealthTextHeading = "Gesundheit"
L.Settings.HealthTextEnabled = "Gesundheit anzeigen"
L.Settings.HealthTextFormat = "Gesundheitsformat"
L.Settings.HealthTextPercent = "Prozent"
L.Settings.HealthTextAbsValue = "Absolutwert"
L.Settings.HealthTextAbsValueAbbreviated = "Absolutwert (gekürzt)"
L.Settings.HealthTextColorMode = "Gesundheitsfarbe"
L.Settings.HealthTextColor = "Statische Gesundheitsfarbe"
L.Settings.HealthTextFont = "Gesundheitsschriftart"
L.Settings.HealthTextFontSize = "Gesundheitsschriftgröße"
L.Settings.HealthTextAnchor = "Gesundheitsanker"
L.Settings.HealthTextOffsetX = "Gesundheitsversatz rechts"
L.Settings.HealthTextOffsetY = "Gesundheitsversatz nach oben"
L.Settings.ResetHealthText = "Gesundheitseinstellungen zurücksetzen"
L.Settings.PreviewHeading = "Vorschau"
L.Settings.PreviewCaption = "%d × %d · dargestellt mit %d%%"
L.Settings.Orientation = "Füllrichtung"
L.Settings.Horizontal = "Quer, dann abwärts"
L.Settings.Vertical = "Abwärts, dann quer"
L.Settings.Stride = "Umbruch alle"
L.Settings.GrowX = "Horizontal wachsen"
L.Settings.GrowRight = "Rechts"
L.Settings.GrowLeft = "Links"
L.Settings.GrowY = "Vertikal wachsen"
L.Settings.GrowDown = "Abwärts"
L.Settings.GrowUp = "Aufwärts"
L.Settings.SpacingX = "Horizontaler Abstand"
L.Settings.SpacingY = "Vertikaler Abstand"

L.Settings.FillHeading = "Füllung"
L.Settings.Spacing = "Abstand"
L.Settings.SpacingHorizontalShort = "H"
L.Settings.SpacingVerticalShort = "V"
L.Settings.FillOrderHeading = "Füllreihenfolge"
L.Settings.FillOrderCaption = "%s · Umbruch alle %d · wächst %s, %s"
L.Settings.AllowGaps = "Leere Zellen darstellen"
L.Settings.AllowGapsHelp =
"An: Ein Spieler, der den Schlachtzug verlässt, lässt seine Zelle leer und nichts anderes verschiebt sich. Aus: Die verbleibenden Hervorhebungen schließen die Lücke, sobald du außerhalb des Kampfes bist."
L.Settings.ClearOnLeave = "Gruppe beim Verlassen der Gruppe leeren"
L.Settings.ClearOnLeaveHelp =
"Aus: Deine Hervorhebungen werden zwischen Schlachtzügen gespeichert. An: Das Verlassen eines Schlachtzugs leert das Raster vollständig – jeden Spieler und jeden Platzhalter –, sodass der nächste bei null beginnt. Ausloggen, Neuladen und erneutes Verbinden zählen nicht als Verlassen."
L.Settings.CombatHelp =
"Hervorhebungen werden nur außerhalb des Kampfes neu aufgebaut. Das Hinzufügen oder Entfernen während eines Kampfes wird gemerkt und im Moment des Kampfendes angewendet; nichts geht verloren, aber das Raster ändert sich nicht mitten im Kampf."
L.Settings.RosterHelp =
"Du kannst Spieler per Drag & Drop in die untenstehende Gruppierung hinein- und herausziehen. Du kannst sie auch auf den Spotlights-Container ziehen, wenn bereits mindestens ein anderer Spieler vorhanden ist."
L.Settings.SlotsHeader = "Konfigurierte Plätze"
L.Settings.RaidHeader = "Schlachtzugsmitglieder"
L.Settings.AddSpacer = "Platzhalter hinzufügen"
L.Settings.NoSlots =
"Noch keine Hervorhebungen konfiguriert. Füge ein Schlachtzugsmitglied aus der Liste daneben hinzu oder zieh eines hierher."
L.Settings.ClearSlots = "Alle Plätze leeren"
L.Settings.ClearSlotsPrompt =
"Jeden konfigurierten Platz entfernen? Spieler und Platzhalter verschwinden gleichermaßen, und das Raster beginnt bei null."
L.Settings.ClearSlotsConfirm = "Leeren"
L.Settings.BlankSlot = "(Platzhalter)"
L.Settings.UnknownSlot = "(leer)"
L.Settings.NotInRaid = "nicht in einem Schlachtzug"
L.Settings.AllSpotlighted = "alle sind hervorgehoben"
L.Settings.UpShort = "^"
L.Settings.DownShort = "v"
L.Settings.RemoveShort = "x"
L.Settings.PlusShort = "+"
L.Settings.AurasEvokerOnly = "Aura-Verfolgung ist eine reine Rufer-Funktion für Macht erspüren, Voraussicht und Verändernde Sande."
L.Settings.Prescience = "Voraussicht"
L.Settings.ShiftingSands = "Verändernde Sande"
L.Settings.Cooldowns = "Abklingzeiten & benutzerdefinierte Auren"
L.Settings.Defensives = "Defensive"
L.Settings.AuraAugmentationOnly = "Voraussicht, Verändernde Sande und Macht erspüren sind nur für Rufer der Verstärkung verfügbar."
L.Settings.AuraTracked = "Überwacht"
L.Settings.AuraFeatureToggle = "%s überwachen"
L.Settings.SensePower = "Macht erspüren"
L.Settings.AuraBar = "Statusleiste"
L.Settings.AuraIcon = "Symbol"
L.Settings.AuraEnabled = "Anzeigen"
L.Settings.AuraColor = "Balkenfarbe"
L.Settings.AuraAlpha = "Deckkraft"
L.Settings.AuraWidth = "Breite"
L.Settings.AuraHeight = "Höhe"
L.Settings.AuraAnchor = "Verankern an"
L.Settings.AuraOffsetX = "Versatz rechts"
L.Settings.AuraOffsetY = "Versatz nach oben"
L.Settings.AuraShowIcon = "Eingebettetes Symbol"
L.Settings.AuraIconSide = "Symbolseite"
L.Settings.AuraIconLeft = "Links vom Balken"
L.Settings.AuraGap = "Abstand"
L.Settings.AuraIconRight = "Rechts vom Balken"
L.Settings.AuraIconWidth = "Breite"
L.Settings.AuraIconHeight = "Höhe"
L.Settings.AuraShowSwipe = "Abklingzeit-Wischer"
L.Settings.AuraShowText = "Dauertext"
L.Settings.AuraFont = "Dauerschriftart"
L.Settings.AuraFontSize = "Dauergröße"
L.Settings.AuraBorder = "Rahmen"
L.Settings.AuraBorderStyle = "Rahmenstil"
L.Settings.AuraBorderSize = "Rahmenstärke"
L.Settings.AuraBorderColor = "Rahmenfarbe"

L.Settings.AuraSummary = "%d × %d · %s · %s · %s"
L.Settings.AuraSummaryHidden = "Ausgeblendet"
L.Settings.AuraSummarySwipeOn = "Wischeffekt an"
L.Settings.AuraSummarySwipeOff = "Wischeffekt aus"
L.Settings.AuraSummaryInlineIcon = "mit Symbol"
L.Settings.AuraSummaryNoInlineIcon = "ohne Symbol"
L.Settings.AuraSummaryBorder = "%dpx Rahmen"
L.Settings.AuraSummaryNoBorder = "kein Rahmen"
L.Settings.AuraReset = "Auf Standard zurücksetzen"
L.Settings.AuraResetConfirm = "Zurücksetzen"
L.Settings.AuraResetPrompt = "Statusleiste und Symbol von %s auf die Standardeinstellungen zurücksetzen?"
L.Settings.AuraResetDisplayPrompt = "%s von %s auf die Standardeinstellungen zurücksetzen?"
L.Settings.AuraResetSpellsPrompt =
"Die von %s überwachten Zauber auf die Standardauswahl zurücksetzen? Selbst hinzugefügte Zauber bleiben erhalten."
L.Settings.AuraGroupCount = "%d/%d"
L.Settings.AuraEnableAll = "Alle aktivieren"
L.Settings.AuraDisableAll = "Alle deaktivieren"
L.Settings.AuraSpellMeta = "%d · %s"
L.Settings.AuraNoTrackedSpells =
"%s überwacht genau einen Aura-Effekt, daher gibt es hier nichts auszuwählen."
L.Settings.AuraNoSpellMatches = "Keine Zauber entsprechen deiner Suche."
L.Settings.AurasRebuildHelp =
"Einige Einstellungen benötigen nach der Anwendung möglicherweise ein Neuladen. Du wirst dazu aufgefordert, sobald du mit dem Anpassen fertig bist."
L.Settings.AuraBuiltinCooldowns = "Verfolgte Abklingzeiten"
L.Settings.AuraBuiltinCooldownsNote =
"Die Anzeige von Macht spüren zeigt diese wichtigen Abklingzeiten auch an, wenn der hervorgehobene Spieler eine davon einsetzt."
L.Settings.AuraBuiltinDefensives = "Verfolgte defensive Fähigkeiten"
L.Settings.AuraBuiltinDefensivesNote =
"Diese defensiven Fähigkeiten anzeigen, wenn der hervorgehobene Spieler eine davon einsetzt."
L.Settings.AuraCustomCooldowns = "Benutzerdefinierte Auren"
L.Settings.AuraCustomCooldownsNote =
"Dies müssen STÄRKUNGSZAUBER sein, die auf Spielern erscheinen, Schmuckstück-Effekte funktionieren beispielsweise. Schwächungszauber und Zauber können hier nicht verfolgt werden, und das Hinzufügen bewirkt überhaupt nichts."
L.Settings.AuraCustomDefensivesNote =
"Defensive Zauber-IDs hinzufügen, die nicht in der mitgelieferten Liste enthalten sind."
L.Settings.AuraCustomAdd = "Hinzufügen"
L.Settings.AuraCustomSpellID = "Zauber-ID"
L.Settings.ReloadPrompt =
"Einige Aura-Einstellungen haben ihre Anzeigen ersetzt statt sie zu ändern, und die Originale bleiben im Speicher, bis du neu lädst.\n\nJetzt neu laden?"
L.Settings.ReloadNow = "Jetzt neu laden"
L.Settings.ReloadLater = "Später"
L.Settings.ImportReloadPrompt = "Die Spotlights-Einstellungen wurden importiert. Die Benutzeroberfläche jetzt neu laden?"

L.Settings.Anchors.TOPLEFT = "Oben links"
L.Settings.Anchors.TOP = "Oben"
L.Settings.Anchors.TOPRIGHT = "Oben rechts"
L.Settings.Anchors.LEFT = "Links"
L.Settings.Anchors.CENTER = "Mitte"
L.Settings.Anchors.RIGHT = "Rechts"
L.Settings.Anchors.BOTTOMLEFT = "Unten links"
L.Settings.Anchors.BOTTOM = "Unten"
L.Settings.Anchors.BOTTOMRIGHT = "Unten rechts"

L.Auras.SensePowerMissing =
"Spotlights kann nicht erkennen, ob Macht spüren aktiv ist, es sei denn, es befindet sich auf einer deiner Aktionsleisten.\n\nNur die von dir aktivierten Abklingzeiten können verfolgt werden, wodurch einige Beschwörungen ausgelassen werden. Für eine vollständige Verfolgung muss Macht spüren aktiv sein, lege es also auf eine Leiste, wenn du es einschalten möchtest."
L.Auras.SensePowerInactive =
"Macht spüren ist nicht aktiv.\n\nNur die von dir aktivierten Abklingzeiten können verfolgt werden, wodurch einige Beschwörungen ausgelassen werden. Für eine vollständige Verfolgung aktiviere bitte Macht spüren."

L.ContextMenu.Title = "Spotlights"
L.ContextMenu.Add = "Diesen Spieler hervorheben"
L.ContextMenu.Remove = "Hervorhebung beenden"

L.DragAssign.HintDrag = "Ziehe %s auf eine Hervorhebung"
L.DragAssign.HintAdd = "%s als Platz %d hinzufügen"
L.DragAssign.HintAppend = "%s ans Ende hinzufügen"
L.DragAssign.HintAlready = "%s belegt bereits Platz %d"
L.DragAssign.HintReorder = "Ziehe %s auf eine Zelle zum Neuordnen oder auf Schlachtzugsmitglieder zum Entfernen"
L.DragAssign.HintMove = "%s auf Platz %d verschieben"
L.DragAssign.HintRemove = "%s entfernen"

L.Preview.Label = "Hervorhebung %d"

L.Mover.Label = "Spotlights"
L.Mover.Unlocked = "Raster entsperrt – ziehe es beliebig, /spotlights mover zum Sperren"
L.Mover.Locked = "Raster gesperrt"
L.Mover.LockedByCombat = "Raster gesperrt: Kampf beginnt"
L.Mover.CombatRefused = "das Raster kann im Kampf nicht bewegt werden"
L.Mover.Reset = "Raster in die Bildschirmmitte zurückgesetzt"
