---@type string, Spotlights
local _, Private = ...

local L = Private.L

L.SlashCommands.Usage = "Comandos:"
L.SlashCommands.Help = "Muestra todos los comandos"
L.SlashCommands.Mover = "Desbloquea la rejilla para arrastrarla"
L.SlashCommands.Recenter = "Devuelve la rejilla al centro de la pantalla"
L.SlashCommands.Add = "Destaca a un miembro de la banda por su nombre"
L.SlashCommands.List = "Lista las ranuras configuradas"
L.SlashCommands.Rescan = "Fuerza a cada ranura ocupada a volver a emparejarse con la lista"
L.SlashCommands.Options = "Abre el panel de ajustes"
L.SlashCommands.OptionsPreview = "Abre el panel de ajustes renovado, aún en construcción"

L.Migration.FromTheFuture =
"los ajustes guardados son de la versión %d pero esta compilación entiende la %d - se han dejado intactos en lugar de degradarlos"

L.Registry.NotLoaded = "los ajustes guardados aún no se han cargado"
L.Registry.AddUsage = "uso: /spotlights add <nombre>"
L.Registry.Unknown = "ningún miembro de la banda coincide con '%s'"
L.Registry.IdentitySecret = "no se puede emparejar '%s' - %d miembro(s) de la banda tienen identidades secretas aquí"
L.Registry.NotInRoster = "ese jugador no está en la banda, así que su nombre no se puede emparejar de forma fiable"
L.Registry.Duplicate = "%s ya ocupa la ranura %d"
L.Registry.NoSuchSlot = "no existe la ranura %d"
L.Registry.Assigned = "la ranura %d destaca a %s"
L.Registry.Deferred = "en combate - los marcos se pondrán al día cuando termine"
L.Registry.Rescanned = "%d ranura(s) reemparejada(s) con la lista"
L.Registry.Empty = "no hay ranuras configuradas - prueba /spotlights add <nombre>"
L.Registry.ListHeader = "%d ranura(s), %d nombre(s) de la lista legibles, %d secreto(s)"
L.Registry.ListPlayer = "  %d. %s |cff808080%s|r"
L.Registry.ListBlank = "  %d. |cff808080(separador)|r"
L.Registry.Absent = "no está en la banda"
L.Registry.Unresolved = "aún sin guid"
L.Registry.ClearedOnLeave = "abandonaste la banda - lista vaciada, según lo configurado"

L.Layout.NotLoaded = "los ajustes guardados aún no se han cargado"

L.Settings.Title = "Spotlights"
L.Settings.CombatRefused = "los ajustes no se pueden abrir en combate"
L.Settings.ClosedByCombat = "ajustes cerrados: entrando en combate"
L.Settings.TabGeneral = "General"
L.Settings.TabAppearance = "Apariencia"
L.Settings.TabGrid = "Rejilla"
L.Settings.TabAuras = "Auras"
L.Settings.TabRoster = "Lista"
L.Settings.TabImportExport = "Importar / Exportar"
L.Settings.ShowMinimapButton = "Mostrar botón del minimapa"
L.Settings.ClickToOpenSettings = "Haz clic para abrir los ajustes"
L.Settings.Import = "Importar"
L.Settings.Export = "Exportar"
L.Settings.ImportError = "Error de importación: %s"
L.Settings.ImportErrorPrefix = "la cadena no empieza por SPOTLIGHTS!"
L.Settings.ImportErrorDecode = "no se ha podido decodificar la cadena"
L.Settings.ImportErrorPayload = "los datos decodificados no son una tabla de ajustes"
L.Settings.Copy = "Copiar"
L.Settings.ToggleMover = "Desbloquear / bloquear"
L.Settings.Recenter = "Volver al centro"
L.Settings.PlacementHeading = "Colocación"
L.Settings.InterfaceHeading = "Interfaz"
L.Settings.UnlockFrames = "Desbloquear los marcos para arrastrarlos"
L.Settings.Scale = "Escala de los marcos"
L.Settings.FrameStrata = "Nivel de los marcos"
L.Settings.SlashHint = "Escribe |cffffd100/spotlights|r para ver todos los comandos."
L.Settings.Strata.BACKGROUND = "Fondo"
L.Settings.Strata.LOW = "Bajo"
L.Settings.Strata.MEDIUM = "Medio"
L.Settings.Strata.HIGH = "Alto"
L.Settings.Strata.DIALOG = "Diálogo"
L.Settings.Strata.FULLSCREEN = "Pantalla completa"
L.Settings.Strata.FULLSCREEN_DIALOG = "Diálogo a pantalla completa"
L.Settings.Strata.TOOLTIP = "Descripción emergente"
L.Settings.FrameHeading = "Marco"
L.Settings.Width = "Ancho del marco"
L.Settings.Height = "Alto del marco"
L.Settings.FrameAlpha = "Opacidad del marco"
L.Settings.BarTexture = "Textura de la barra"
L.Settings.TextureMissing = "%s (no cargada)"
L.Settings.ShowAbsorb = "Mostrar absorciones"
L.Settings.OutOfRangeAlpha = "Alfa fuera de alcance"
L.Settings.DeadAlpha = "Alfa al morir"
L.Settings.ColorClass = "Color de clase"
L.Settings.ColorStatic = "Color estático"
L.Settings.HealthColorMode = "Color de la barra"
L.Settings.HealthColor = "Color estático de la barra"
L.Settings.HealthBgColor = "Color de fondo"
L.Settings.ResetFrame = "Restablecer ajustes del marco"
L.Settings.NameHeading = "Nombre"
L.Settings.NameColorMode = "Color del nombre"
L.Settings.NameColor = "Color estático del nombre"
L.Settings.NameFont = "Fuente del nombre"
L.Settings.NameFontSize = "Tamaño de fuente del nombre"
L.Settings.NameAnchor = "Anclaje del nombre"
L.Settings.NameOffsetX = "Desplazamiento del nombre a la derecha"
L.Settings.NameOffsetY = "Desplazamiento del nombre hacia arriba"
L.Settings.ResetName = "Restablecer ajustes del nombre"
L.Settings.HealthTextHeading = "Salud"
L.Settings.HealthTextEnabled = "Mostrar salud"
L.Settings.HealthTextFormat = "Formato de la salud"
L.Settings.HealthTextPercent = "Porcentaje"
L.Settings.HealthTextAbsValue = "Valor absoluto"
L.Settings.HealthTextAbsValueAbbreviated = "Valor absoluto (abreviado)"
L.Settings.HealthTextColorMode = "Color de la salud"
L.Settings.HealthTextColor = "Color estático de la salud"
L.Settings.HealthTextFont = "Fuente de la salud"
L.Settings.HealthTextFontSize = "Tamaño de fuente de la salud"
L.Settings.HealthTextAnchor = "Anclaje de la salud"
L.Settings.HealthTextOffsetX = "Desplazamiento de la salud a la derecha"
L.Settings.HealthTextOffsetY = "Desplazamiento de la salud hacia arriba"
L.Settings.ResetHealthText = "Restablecer ajustes de la salud"
L.Settings.PreviewHeading = "Vista previa"
L.Settings.PreviewCaption = "%d × %d · mostrado al %d%%"
L.Settings.Orientation = "Dirección de relleno"
L.Settings.Horizontal = "En horizontal, luego abajo"
L.Settings.Vertical = "Hacia abajo, luego a los lados"
L.Settings.Stride = "Ajustar cada"
L.Settings.GrowX = "Crecer horizontalmente"
L.Settings.GrowRight = "Derecha"
L.Settings.GrowLeft = "Izquierda"
L.Settings.GrowY = "Crecer verticalmente"
L.Settings.GrowDown = "Abajo"
L.Settings.GrowUp = "Arriba"
L.Settings.SpacingX = "Espaciado horizontal"
L.Settings.SpacingY = "Espaciado vertical"

L.Settings.FillHeading = "Relleno"
L.Settings.Spacing = "Espaciado"
L.Settings.SpacingHorizontalShort = "H"
L.Settings.SpacingVerticalShort = "V"
L.Settings.FillOrderHeading = "Orden de relleno"
L.Settings.FillOrderCaption = "%s · ajusta cada %d · crece %s, %s"
L.Settings.AllowGaps = "Mostrar celdas vacías"
L.Settings.AllowGapsHelp =
"Activado, un jugador que abandona la banda deja su celda vacía y nada más se mueve. Desactivado, los destacados restantes cierran el hueco en cuanto salgas de combate."
L.Settings.ClearOnLeave = "Vaciar la lista al abandonar el grupo"
L.Settings.ClearOnLeaveHelp =
"Desactivado, tus destacados se recuerdan entre bandas. Activado, abandonar una banda vacía la rejilla por completo - cada jugador y cada separador - para que la siguiente empiece desde cero. Cerrar sesión, recargar y reconectar no cuentan como abandonar."
L.Settings.CombatHelp =
"Los destacados solo se reconstruyen fuera de combate. Añadir o quitar uno durante una pelea se recuerda y se aplica en el momento en que termina el combate; no se pierde nada, pero la rejilla no cambiará a mitad de combate."
L.Settings.RosterHelp =
"Puedes arrastrar y soltar jugadores dentro y fuera de la agrupación de abajo. También puedes arrastrarlos sobre el contenedor de Spotlights si ya hay al menos otro jugador presente."
L.Settings.SlotsHeader = "Ranuras configuradas"
L.Settings.RaidHeader = "Miembros de la banda"
L.Settings.AddSpacer = "Añadir un separador"
L.Settings.NoSlots =
"Todavía no hay nadie destacado. Añade un miembro de la banda desde la lista de al lado, o arrastra uno hasta aquí."
L.Settings.ClearSlots = "Vaciar todas las ranuras"
L.Settings.ClearSlotsPrompt =
"¿Quitar todas las ranuras configuradas? Se van tanto los jugadores como los separadores, y la rejilla empieza de cero."
L.Settings.ClearSlotsConfirm = "Vaciar"
L.Settings.BlankSlot = "(separador)"
L.Settings.UnknownSlot = "(vacío)"
L.Settings.NotInRaid = "no estás en una banda"
L.Settings.AllSpotlighted = "todos están destacados"
L.Settings.UpShort = "^"
L.Settings.DownShort = "v"
L.Settings.RemoveShort = "x"
L.Settings.PlusShort = "+"
L.Settings.PresetsHeading = "Preajustes"
L.Settings.PresetsCount = "%d guardados"
L.Settings.PresetsNone =
"Aún no hay preajustes guardados. Guarda las posiciones configuradas para crear uno."
L.Settings.PresetSave = "Guardar"
L.Settings.PresetDelete = "Eliminar"
L.Settings.PresetSavePrompt = "Nombra este preajuste:"
L.Settings.PresetOverwritePrompt = "Ya existe un preajuste llamado «%s». ¿Reemplazarlo?"
L.Settings.PresetOverwriteConfirm = "Reemplazar"
L.Settings.PresetDeletePrompt =
"¿Eliminar el preajuste «%s»? Tus posiciones configuradas no se modifican."
L.Settings.PresetImportAdd = "Añadir preajuste"
L.Settings.PresetImportErrorPrefix = "la cadena no es un preajuste de Spotlights"
L.Settings.PresetImportErrorPayload = "los datos decodificados no son una lista de posiciones"
L.Settings.AurasEvokerOnly =
"El seguimiento de auras es una función exclusiva de Evocador para Detectar poder, Presciencia y Arenas cambiantes."
L.Settings.Prescience = "Presciencia"
L.Settings.ShiftingSands = "Arenas cambiantes"
L.Settings.Cooldowns = "Reutilizaciones y auras personalizadas"
L.Settings.Defensives = "Defensivos"
L.Settings.AuraAugmentationOnly = "Presciencia, Arenas cambiantes y Detectar poder solo están disponibles para Evocadores de Aumento."
L.Settings.AuraTracked = "Seguimiento"
L.Settings.AuraFeatureToggle = "Seguir %s"
L.Settings.SensePower = "Detectar poder"
L.Settings.AuraBar = "Barra de estado"
L.Settings.AuraIcon = "Icono"
L.Settings.AuraEnabled = "Mostrar"
L.Settings.AuraColor = "Color de la barra"
L.Settings.AuraAlpha = "Opacidad"
L.Settings.AuraWidth = "Ancho"
L.Settings.AuraHeight = "Alto"
L.Settings.AuraAnchor = "Anclar a"
L.Settings.AuraOffsetX = "Desplazamiento a la derecha"
L.Settings.AuraOffsetY = "Desplazamiento hacia arriba"
L.Settings.AuraShowIcon = "Icono en línea"
L.Settings.AuraIconSide = "Lado del icono"
L.Settings.AuraIconLeft = "A la izquierda de la barra"
L.Settings.AuraGap = "Separación"
L.Settings.AuraIconRight = "A la derecha de la barra"
L.Settings.AuraIconWidth = "Ancho"
L.Settings.AuraIconHeight = "Alto"
L.Settings.AuraShowSwipe = "Barrido de reutilización"
L.Settings.AuraShowText = "Texto de duración"
L.Settings.AuraFont = "Fuente de duración"
L.Settings.AuraFontSize = "Tamaño de duración"
L.Settings.AuraBorder = "Borde"
L.Settings.AuraBorderStyle = "Estilo del borde"
L.Settings.AuraBorderSize = "Grosor del borde"
L.Settings.AuraBorderColor = "Color del borde"

L.Settings.AuraSummary = "%d × %d · %s · %s · %s"
L.Settings.AuraSummaryHidden = "Oculto"
L.Settings.AuraSummarySwipeOn = "barrido activado"
L.Settings.AuraSummarySwipeOff = "barrido desactivado"
L.Settings.AuraSummaryInlineIcon = "con icono"
L.Settings.AuraSummaryNoInlineIcon = "sin icono"
L.Settings.AuraSummaryBorder = "borde de %dpx"
L.Settings.AuraSummaryNoBorder = "sin borde"
L.Settings.AuraReset = "Restablecer valores predeterminados"
L.Settings.AuraResetConfirm = "Restablecer"
L.Settings.AuraResetPrompt = "¿Restablecer la barra de estado y el icono de %s a sus ajustes predeterminados?"
L.Settings.AuraResetDisplayPrompt = "¿Restablecer «%s» de %s a sus ajustes predeterminados?"
L.Settings.AuraResetSpellsPrompt =
"¿Restablecer los hechizos que %s sigue a la selección predeterminada? Los hechizos que hayas añadido se conservan."
L.Settings.AuraGroupCount = "%d/%d"
L.Settings.AuraEnableAll = "Activar todo"
L.Settings.AuraDisableAll = "Desactivar todo"
L.Settings.AuraSpellMeta = "%d · %s"
L.Settings.AuraNoTrackedSpells = "%s vigila un aura concreta, así que aquí no hay nada que elegir."
L.Settings.AuraNoSpellMatches = "Ningún hechizo coincide con tu búsqueda."
L.Settings.AurasRebuildHelp =
"Algunos ajustes pueden requerir una recarga tras aplicarse. Se te pedirá que lo hagas cuando termines de personalizar."
L.Settings.AuraBuiltinCooldowns = "Reutilizaciones rastreadas"
L.Settings.AuraBuiltinCooldownsNote =
"La visualización de Percibir poder también muestra estas reutilizaciones importantes cuando el jugador destacado usa una."
L.Settings.AuraBuiltinDefensives = "Habilidades defensivas rastreadas"
L.Settings.AuraBuiltinDefensivesNote =
"Mostrar estas habilidades defensivas cuando el jugador destacado use una."
L.Settings.AuraCustomCooldowns = "Auras personalizadas"
L.Settings.AuraCustomCooldownsNote =
"Estas deben ser BENEFICIOS que aparezcan en los jugadores, para que funcionen los efectos de abalorios. Los perjuicios y los lanzamientos no se pueden rastrear aquí, y añadir uno no hará absolutamente nada."
L.Settings.AuraCustomDefensivesNote =
"Añade IDs de hechizos defensivos que no estén en la lista incluida."
L.Settings.AuraCustomAdd = "Añadir"
L.Settings.AuraCustomSpellID = "ID de hechizo"
L.Settings.ReloadPrompt =
"Algunos ajustes de auras reemplazaron sus visualizaciones en lugar de cambiarlas, y las originales permanecen en memoria hasta que recargues.\n\n¿Recargar ahora?"
L.Settings.ReloadNow = "Recargar ahora"
L.Settings.ReloadLater = "Más tarde"
L.Settings.ImportReloadPrompt = "Se han importado los ajustes de Spotlights. ¿Recargar la interfaz ahora?"

L.Settings.Anchors.TOPLEFT = "Arriba a la izquierda"
L.Settings.Anchors.TOP = "Arriba"
L.Settings.Anchors.TOPRIGHT = "Arriba a la derecha"
L.Settings.Anchors.LEFT = "Izquierda"
L.Settings.Anchors.CENTER = "Centro"
L.Settings.Anchors.RIGHT = "Derecha"
L.Settings.Anchors.BOTTOMLEFT = "Abajo a la izquierda"
L.Settings.Anchors.BOTTOM = "Abajo"
L.Settings.Anchors.BOTTOMRIGHT = "Abajo a la derecha"

L.Auras.SensePowerMissing =
"Spotlights no puede saber si Percibir poder está activo a menos que esté en una de tus barras de acción.\n\nSolo se pueden rastrear las reutilizaciones que hayas activado, lo que deja fuera algunas invocaciones. Para un rastreo completo, Percibir poder debe estar activo, así que ponlo en una barra si deseas activarlo."
L.Auras.SensePowerInactive =
"Percibir poder no está activo.\n\nSolo se pueden rastrear las reutilizaciones que hayas activado, lo que deja fuera algunas invocaciones. Para un rastreo completo, activa Percibir poder."

L.ContextMenu.Title = "Spotlights"
L.ContextMenu.Add = "Destacar a este jugador"
L.ContextMenu.Remove = "Dejar de destacar"

L.DragAssign.HintDrag = "Arrastra a %s sobre un destacado"
L.DragAssign.HintAdd = "Añadir a %s como ranura %d"
L.DragAssign.HintAppend = "Añadir a %s al final"
L.DragAssign.HintAlready = "%s ya ocupa la ranura %d"
L.DragAssign.HintReorder = "Arrastra a %s a una celda para reordenar, o a Miembros de la banda para quitarlo"
L.DragAssign.HintMove = "Mover a %s a la ranura %d"
L.DragAssign.HintRemove = "Quitar a %s"

L.Preview.Label = "Destacado %d"

L.Mover.Label = "Spotlights"
L.Mover.Unlocked = "rejilla desbloqueada - arrástrala a cualquier sitio, /spotlights mover para bloquear"
L.Mover.Locked = "rejilla bloqueada"
L.Mover.LockedByCombat = "rejilla bloqueada: entrando en combate"
L.Mover.CombatRefused = "no se puede mover la rejilla en combate"
L.Mover.Reset = "rejilla devuelta al centro de la pantalla"
