---@type string, Spotlights
local _, Private = ...

local L = Private.L

L.SlashCommands.Usage = "Comandos:"
L.SlashCommands.Help = "Lista todos os comandos"
L.SlashCommands.Mover = "Desbloqueia a grade para arrastar"
L.SlashCommands.Recenter = "Retorna a grade ao centro da tela"
L.SlashCommands.Add = "Destaca um membro da raide pelo nome"
L.SlashCommands.List = "Lista os espaços configurados"
L.SlashCommands.Rescan = "Força cada espaço ocupado a corresponder novamente à lista"
L.SlashCommands.Options = "Abre o painel de configurações"
L.SlashCommands.OptionsPreview = "Abre o painel de configurações reformulado, ainda em construção"

L.Migration.FromTheFuture =
"as configurações salvas são da versão %d mas esta build entende %d - elas foram mantidas intactas em vez de rebaixadas"

L.Registry.NotLoaded = "as configurações salvas ainda não foram carregadas"
L.Registry.AddUsage = "uso: /spotlights add <nome>"
L.Registry.Unknown = "nenhum membro da raide corresponde a '%s'"
L.Registry.IdentitySecret = "não é possível corresponder '%s' - %d membro(s) da raide têm identidades secretas aqui"
L.Registry.NotInRoster =
"esse jogador não está na raide, então o nome dele não pode ser correspondido de forma confiável"
L.Registry.Duplicate = "%s já ocupa o espaço %d"
L.Registry.NoSuchSlot = "não existe o espaço %d"
L.Registry.Assigned = "o espaço %d destaca %s"
L.Registry.Deferred = "em combate - os quadros se atualizam quando ele terminar"
L.Registry.Rescanned = "%d espaço(s) correspondido(s) novamente à lista"
L.Registry.Empty = "nenhum espaço configurado - tente /spotlights add <nome>"
L.Registry.ListHeader = "%d espaço(s), %d nome(s) da lista legíveis, %d secreto(s)"
L.Registry.ListPlayer = "  %d. %s |cff808080%s|r"
L.Registry.ListBlank = "  %d. |cff808080(espaçador)|r"
L.Registry.Absent = "não está na raide"
L.Registry.Unresolved = "ainda sem guid"
L.Registry.ClearedOnLeave = "saiu da raide - lista limpa, conforme configurado"

L.Layout.NotLoaded = "as configurações salvas ainda não foram carregadas"

L.Settings.Title = "Spotlights"
L.Settings.CombatRefused = "as configurações não podem ser abertas em combate"
L.Settings.ClosedByCombat = "configurações fechadas: entrando em combate"
L.Settings.TabGeneral = "Geral"
L.Settings.TabAppearance = "Aparência"
L.Settings.TabGrid = "Grade"
L.Settings.TabAuras = "Auras"
L.Settings.TabRoster = "Lista"
L.Settings.TabImportExport = "Importar / Exportar"
L.Settings.ShowMinimapButton = "Mostrar botão do minimapa"
L.Settings.ClickToOpenSettings = "Clique para abrir as configurações"
L.Settings.Import = "Importar"
L.Settings.Export = "Exportar"
L.Settings.ImportError = "Falha na importação: %s"
L.Settings.ImportErrorPrefix = "a sequência não começa com SPOTLIGHTS!"
L.Settings.ImportErrorDecode = "não foi possível decodificar a sequência"
L.Settings.ImportErrorPayload = "os dados decodificados não são uma tabela de configurações"
L.Settings.Copy = "Copiar"
L.Settings.ToggleMover = "Desbloquear / bloquear"
L.Settings.Recenter = "Voltar ao centro"
L.Settings.PlacementHeading = "Posicionamento"
L.Settings.InterfaceHeading = "Interface"
L.Settings.UnlockFrames = "Desbloquear os quadros para arrastar"
L.Settings.Scale = "Escala dos quadros"
L.Settings.FrameStrata = "Nível dos quadros"
L.Settings.SlashHint = "Digite |cffffd100/spotlights|r para ver todos os comandos."
L.Settings.Strata.BACKGROUND = "Plano de fundo"
L.Settings.Strata.LOW = "Baixo"
L.Settings.Strata.MEDIUM = "Médio"
L.Settings.Strata.HIGH = "Alto"
L.Settings.Strata.DIALOG = "Diálogo"
L.Settings.Strata.FULLSCREEN = "Tela cheia"
L.Settings.Strata.FULLSCREEN_DIALOG = "Diálogo em tela cheia"
L.Settings.Strata.TOOLTIP = "Dica"
L.Settings.FrameHeading = "Quadro"
L.Settings.Width = "Largura do quadro"
L.Settings.Height = "Altura do quadro"
L.Settings.FrameAlpha = "Opacidade do quadro"
L.Settings.BarTexture = "Textura da barra"
L.Settings.TextureMissing = "%s (não carregada)"
L.Settings.ShowAbsorb = "Mostrar absorções"
L.Settings.OutOfRangeAlpha = "Alfa fora de alcance"
L.Settings.DeadAlpha = "Alfa de morto"
L.Settings.ColorClass = "Cor da classe"
L.Settings.ColorStatic = "Cor estática"
L.Settings.HealthColorMode = "Cor da barra"
L.Settings.HealthColor = "Cor estática da barra"
L.Settings.HealthBgColor = "Cor de fundo"
L.Settings.ResetFrame = "Redefinir configurações do quadro"
L.Settings.NameHeading = "Nome"
L.Settings.NameColorMode = "Cor do nome"
L.Settings.NameColor = "Cor estática do nome"
L.Settings.NameFont = "Fonte do nome"
L.Settings.NameFontSize = "Tamanho da fonte do nome"
L.Settings.NameAnchor = "Ancoragem do nome"
L.Settings.NameOffsetX = "Deslocamento do nome à direita"
L.Settings.NameOffsetY = "Deslocamento do nome para cima"
L.Settings.ResetName = "Redefinir configurações do nome"
L.Settings.HealthTextHeading = "Vida"
L.Settings.HealthTextEnabled = "Mostrar vida"
L.Settings.HealthTextFormat = "Formato da vida"
L.Settings.HealthTextPercent = "Porcentagem"
L.Settings.HealthTextAbsValue = "Valor absoluto"
L.Settings.HealthTextAbsValueAbbreviated = "Valor absoluto (abreviado)"
L.Settings.HealthTextColorMode = "Cor da vida"
L.Settings.HealthTextColor = "Cor estática da vida"
L.Settings.HealthTextFont = "Fonte da vida"
L.Settings.HealthTextFontSize = "Tamanho da fonte da vida"
L.Settings.HealthTextAnchor = "Ancoragem da vida"
L.Settings.HealthTextOffsetX = "Deslocamento da vida à direita"
L.Settings.HealthTextOffsetY = "Deslocamento da vida para cima"
L.Settings.ResetHealthText = "Redefinir configurações da vida"
L.Settings.PreviewHeading = "Prévia"
L.Settings.PreviewCaption = "%d × %d · exibido a %d%%"
L.Settings.Orientation = "Direção de preenchimento"
L.Settings.Horizontal = "Ao longo, depois para baixo"
L.Settings.Vertical = "Para baixo, depois ao longo"
L.Settings.Stride = "Quebrar a cada"
L.Settings.GrowX = "Crescer horizontalmente"
L.Settings.GrowRight = "Direita"
L.Settings.GrowLeft = "Esquerda"
L.Settings.GrowY = "Crescer verticalmente"
L.Settings.GrowDown = "Baixo"
L.Settings.GrowUp = "Cima"
L.Settings.SpacingX = "Espaçamento horizontal"
L.Settings.SpacingY = "Espaçamento vertical"

L.Settings.FillHeading = "Preenchimento"
L.Settings.Spacing = "Espaçamento"
L.Settings.SpacingHorizontalShort = "H"
L.Settings.SpacingVerticalShort = "V"
L.Settings.FillOrderHeading = "Ordem de preenchimento"
L.Settings.FillOrderCaption = "%s · quebra a cada %d · cresce %s, %s"
L.Settings.AllowGaps = "Renderizar células vazias"
L.Settings.AllowGapsHelp =
"Ativado, um jogador que sai da raide deixa sua célula vazia e nada mais se move. Desativado, os destaques restantes fecham o espaço assim que você sair do combate."
L.Settings.ClearOnLeave = "Limpar a lista ao sair do grupo"
L.Settings.ClearOnLeaveHelp =
"Desativado, seus destaques são lembrados entre as raides. Ativado, sair de uma raide esvazia a grade completamente - cada jogador e cada espaçador - para que a próxima comece do zero. Deslogar, recarregar e reconectar não contam como sair."
L.Settings.CombatHelp =
"Os destaques são reconstruídos apenas fora do combate. Adicionar ou remover um durante uma luta é lembrado e aplicado no momento em que o combate termina; nada é perdido, mas a grade não mudará no meio do pull."
L.Settings.RosterHelp =
"Você pode arrastar e soltar jogadores para dentro e fora do agrupamento abaixo. Você também pode arrastá-los sobre o contêiner Spotlights se pelo menos um outro jogador já estiver presente."
L.Settings.SlotsHeader = "Espaços configurados"
L.Settings.RaidHeader = "Membros da raide"
L.Settings.AddSpacer = "Adicionar um espaçador"
L.Settings.BlankSlot = "(espaçador)"
L.Settings.UnknownSlot = "(vazio)"
L.Settings.NotInRaid = "não está em uma raide"
L.Settings.AllSpotlighted = "todos estão em destaque"
L.Settings.UpShort = "^"
L.Settings.DownShort = "v"
L.Settings.RemoveShort = "x"
L.Settings.PlusShort = "+"
L.Settings.AurasRequiresTwelveOne =
"As exibições de aura precisam da atualização 12.1 ou posterior. Este cliente não tem o sistema em que elas se baseiam, então o resto desta aba fica oculto em vez de mostrado sem fazer nada."
L.Settings.AurasEvokerOnly =
"O rastreamento de auras é um recurso exclusivo de Evocador para Detectar Poder, Presciência e Areias Cambiantes."
L.Settings.Prescience = "Presciência"
L.Settings.ShiftingSands = "Areias Cambiantes"
L.Settings.Cooldowns = "Recargas e auras personalizadas"
L.Settings.Defensives = "Defensivos"
L.Settings.AuraAugmentationOnly = "Presciência, Areias Cambiantes e Detectar Poder só estão disponíveis para Evocadores de Aprimoramento."
L.Settings.AuraTracked = "Rastreadas"
L.Settings.AuraFeatureToggle = "Rastrear %s"
L.Settings.SensePower = "Detectar Poder"
L.Settings.AuraBar = "Barra de status"
L.Settings.AuraIcon = "Ícone"
L.Settings.AuraEnabled = "Mostrar"
L.Settings.AuraColor = "Cor da barra"
L.Settings.AuraAlpha = "Opacidade"
L.Settings.AuraWidth = "Largura"
L.Settings.AuraHeight = "Altura"
L.Settings.AuraAnchor = "Ancorar em"
L.Settings.AuraOffsetX = "Deslocamento à direita"
L.Settings.AuraOffsetY = "Deslocamento para cima"
L.Settings.AuraShowIcon = "Ícone embutido"
L.Settings.AuraIconSide = "Lado do ícone"
L.Settings.AuraIconLeft = "À esquerda da barra"
L.Settings.AuraGap = "Espaçamento"
L.Settings.AuraIconRight = "À direita da barra"
L.Settings.AuraIconWidth = "Largura"
L.Settings.AuraIconHeight = "Altura"
L.Settings.AuraShowSwipe = "Varredura de recarga"
L.Settings.AuraShowText = "Texto de duração"
L.Settings.AuraFont = "Fonte da duração"
L.Settings.AuraFontSize = "Tamanho da duração"
L.Settings.AuraBorder = "Borda"
L.Settings.AuraBorderStyle = "Estilo da borda"
L.Settings.AuraBorderSize = "Espessura da borda"
L.Settings.AuraBorderColor = "Cor da borda"

L.Settings.AuraSummary = "%d × %d · %s · %s · %s"
L.Settings.AuraSummaryHidden = "Oculto"
L.Settings.AuraSummarySwipeOn = "varredura ativada"
L.Settings.AuraSummarySwipeOff = "varredura desativada"
L.Settings.AuraSummaryInlineIcon = "com ícone"
L.Settings.AuraSummaryNoInlineIcon = "sem ícone"
L.Settings.AuraSummaryBorder = "borda de %dpx"
L.Settings.AuraSummaryNoBorder = "sem borda"
L.Settings.AuraReset = "Restaurar padrões"
L.Settings.AuraResetConfirm = "Restaurar"
L.Settings.AuraResetPrompt = "Restaurar a barra de status e o ícone de %s para suas configurações padrão?"
L.Settings.AurasRebuildHelp =
"Algumas configurações podem precisar de um recarregamento após a aplicação. Você será solicitado a fazê-lo quando terminar de personalizar."
L.Settings.AuraBuiltinCooldowns = "Recargas rastreadas"
L.Settings.AuraBuiltinCooldownsNote =
"A exibição de Sentir Poder também mostra essas grandes recargas quando o jogador em destaque usa uma."
L.Settings.AuraBuiltinDefensives = "Defensivos rastreados"
L.Settings.AuraBuiltinDefensivesNote =
"Mostrar essas habilidades defensivas quando o jogador em destaque usar uma."
L.Settings.AuraCustomCooldowns = "Auras personalizadas"
L.Settings.AuraCustomCooldownsNote =
"Estas devem ser BÊNÇÃOS que aparecem nos jogadores, para que efeitos de berloques funcionem. Maldições e conjurações não podem ser rastreadas aqui, e adicionar uma não fará absolutamente nada."
L.Settings.AuraCustomDefensivesNote =
"Adicione IDs de feitiços defensivos que não estejam na lista incluída."
L.Settings.AuraCustomAdd = "Adicionar"
L.Settings.AuraCustomSpellID = "ID de magia"
L.Settings.ReloadPrompt =
"Algumas configurações de aura substituíram suas exibições em vez de alterá-las, e as originais permanecem na memória até você recarregar.\n\nRecarregar agora?"
L.Settings.ReloadNow = "Recarregar agora"
L.Settings.ReloadLater = "Mais tarde"
L.Settings.ImportReloadPrompt = "As configurações do Spotlights foram importadas. Recarregar a interface agora?"

L.Settings.Anchors.TOPLEFT = "Superior esquerdo"
L.Settings.Anchors.TOP = "Superior"
L.Settings.Anchors.TOPRIGHT = "Superior direito"
L.Settings.Anchors.LEFT = "Esquerda"
L.Settings.Anchors.CENTER = "Centro"
L.Settings.Anchors.RIGHT = "Direita"
L.Settings.Anchors.BOTTOMLEFT = "Inferior esquerdo"
L.Settings.Anchors.BOTTOM = "Inferior"
L.Settings.Anchors.BOTTOMRIGHT = "Inferior direito"

L.Auras.SensePowerMissing =
"Spotlights não consegue saber se Sentir Poder está ativo a menos que esteja em uma de suas barras de ação.\n\nApenas as recargas que você habilitou podem ser rastreadas, o que exclui algumas invocações. Para rastreamento completo, Sentir Poder deve estar ativo, então coloque-o em uma barra se desejar ativá-lo."
L.Auras.SensePowerInactive =
"Sentir Poder não está ativo.\n\nApenas as recargas que você habilitou podem ser rastreadas, o que exclui algumas invocações. Para rastreamento completo, por favor ative Sentir Poder."

L.ContextMenu.Title = "Spotlights"
L.ContextMenu.Add = "Destacar este jogador"
L.ContextMenu.Remove = "Parar de destacar"

L.DragAssign.HintDrag = "Arraste %s até um destaque"
L.DragAssign.HintAdd = "Adicionar %s como espaço %d"
L.DragAssign.HintAppend = "Adicionar %s ao final"
L.DragAssign.HintAlready = "%s já ocupa o espaço %d"
L.DragAssign.HintReorder = "Arraste %s até uma célula para reordenar, ou até Membros da raide para remover"
L.DragAssign.HintMove = "Mover %s para o espaço %d"
L.DragAssign.HintRemove = "Remover %s"

L.Preview.Label = "Destaque %d"

L.Mover.Label = "Spotlights"
L.Mover.Unlocked = "grade desbloqueada - arraste para qualquer lugar, /spotlights mover para bloquear"
L.Mover.Locked = "grade bloqueada"
L.Mover.LockedByCombat = "grade bloqueada: entrando em combate"
L.Mover.CombatRefused = "não é possível mover a grade em combate"
L.Mover.Reset = "grade retornada ao centro da tela"
