---@type string, Spotlights
local _, Private = ...

local L = Private.L

L.SlashCommands.Usage = "Команды:"
L.SlashCommands.Help = "Показывает все команды"
L.SlashCommands.Mover = "Разблокирует сетку для перетаскивания"
L.SlashCommands.Recenter = "Возвращает сетку в центр экрана"
L.SlashCommands.Add = "Выделяет участника рейда по имени"
L.SlashCommands.List = "Показывает настроенные слоты"
L.SlashCommands.Rescan = "Заставляет каждый занятый слот заново сопоставиться с составом"
L.SlashCommands.Options = "Открывает панель настроек"
L.SlashCommands.OptionsPreview = "Открывает переработанную панель настроек, ещё не завершённую"

L.Migration.FromTheFuture =
"сохранённые настройки версии %d, но эта сборка понимает %d — они оставлены без изменений, а не понижены"

L.Registry.NotLoaded = "сохранённые настройки ещё не загружены"
L.Registry.AddUsage = "использование: /spotlights add <имя>"
L.Registry.Unknown = "нет участника рейда, соответствующего '%s'"
L.Registry.IdentitySecret = "невозможно сопоставить '%s' — %d участник(ов) рейда имеют скрытые личности"
L.Registry.NotInRoster = "этот игрок не в рейде, поэтому его имя нельзя надёжно сопоставить"
L.Registry.Duplicate = "%s уже занимает слот %d"
L.Registry.NoSuchSlot = "слота %d не существует"
L.Registry.Assigned = "слот %d выделяет %s"
L.Registry.Deferred = "в бою — рамки обновятся, когда он закончится"
L.Registry.Rescanned = "заново сопоставлено %d слот(ов) с составом"
L.Registry.Empty = "слоты не настроены — попробуйте /spotlights add <имя>"
L.Registry.ListHeader = "%d слот(ов), %d имён из состава читаемы, %d скрыто"
L.Registry.ListPlayer = "  %d. %s |cff808080%s|r"
L.Registry.ListBlank = "  %d. |cff808080(разделитель)|r"
L.Registry.Absent = "не в рейде"
L.Registry.Unresolved = "нет guid"
L.Registry.ClearedOnLeave = "покинул рейд — состав очищен, как настроено"

L.Layout.NotLoaded = "сохранённые настройки ещё не загружены"

L.Settings.Title = "Spotlights"
L.Settings.CombatRefused = "настройки нельзя открыть в бою"
L.Settings.ClosedByCombat = "настройки закрыты: вход в бой"
L.Settings.TabGeneral = "Общие"
L.Settings.TabAppearance = "Внешний вид"
L.Settings.TabGrid = "Сетка"
L.Settings.TabAuras = "Ауры"
L.Settings.TabRoster = "Состав"
L.Settings.TabImportExport = "Импорт / Экспорт"
L.Settings.ShowMinimapButton = "Показывать кнопку миникарты"
L.Settings.ClickToOpenSettings = "Нажмите, чтобы открыть настройки"
L.Settings.Import = "Импорт"
L.Settings.Export = "Экспорт"
L.Settings.ImportError = "Не удалось импортировать: %s"
L.Settings.ImportErrorPrefix = "строка не начинается с SPOTLIGHTS!"
L.Settings.ImportErrorDecode = "не удалось декодировать строку"
L.Settings.ImportErrorPayload = "декодированные данные не являются таблицей настроек"
L.Settings.Copy = "Копировать"
L.Settings.ToggleMover = "Разблокировать / заблокировать"
L.Settings.Recenter = "Вернуть в центр"
L.Settings.PlacementHeading = "Размещение"
L.Settings.InterfaceHeading = "Интерфейс"
L.Settings.UnlockFrames = "Разблокировать рамки для перемещения"
L.Settings.Scale = "Масштаб рамок"
L.Settings.FrameStrata = "Слой рамок"
L.Settings.SlashHint = "Введите |cffffd100/spotlights|r, чтобы увидеть все команды."
L.Settings.Strata.BACKGROUND = "Фон"
L.Settings.Strata.LOW = "Низкий"
L.Settings.Strata.MEDIUM = "Средний"
L.Settings.Strata.HIGH = "Высокий"
L.Settings.Strata.DIALOG = "Диалог"
L.Settings.Strata.FULLSCREEN = "Полный экран"
L.Settings.Strata.FULLSCREEN_DIALOG = "Полноэкранный диалог"
L.Settings.Strata.TOOLTIP = "Подсказка"
L.Settings.FrameHeading = "Рамка"
L.Settings.Width = "Ширина рамки"
L.Settings.Height = "Высота рамки"
L.Settings.FrameAlpha = "Прозрачность рамки"
L.Settings.BarTexture = "Текстура полосы"
L.Settings.TextureMissing = "%s (не загружена)"
L.Settings.ShowAbsorb = "Показывать поглощения"
L.Settings.OutOfRangeAlpha = "Прозрачность вне дальности"
L.Settings.DeadAlpha = "Прозрачность мёртвых"
L.Settings.ColorClass = "Цвет класса"
L.Settings.ColorStatic = "Статичный цвет"
L.Settings.HealthColorMode = "Цвет полосы"
L.Settings.HealthColor = "Статичный цвет полосы"
L.Settings.HealthBgColor = "Цвет фона"
L.Settings.ResetFrame = "Сбросить настройки рамки"
L.Settings.NameHeading = "Имя"
L.Settings.NameColorMode = "Цвет имени"
L.Settings.NameColor = "Статичный цвет имени"
L.Settings.NameFont = "Шрифт имени"
L.Settings.NameFontSize = "Размер шрифта имени"
L.Settings.NameAnchor = "Привязка имени"
L.Settings.NameOffsetX = "Смещение имени вправо"
L.Settings.NameOffsetY = "Смещение имени вверх"
L.Settings.ResetName = "Сбросить настройки имени"
L.Settings.HealthTextHeading = "Здоровье"
L.Settings.HealthTextEnabled = "Показывать здоровье"
L.Settings.HealthTextFormat = "Формат здоровья"
L.Settings.HealthTextPercent = "Проценты"
L.Settings.HealthTextAbsValue = "Абсолютное значение"
L.Settings.HealthTextAbsValueAbbreviated = "Абсолютное значение (сокращённо)"
L.Settings.HealthTextColorMode = "Цвет здоровья"
L.Settings.HealthTextColor = "Статичный цвет здоровья"
L.Settings.HealthTextFont = "Шрифт здоровья"
L.Settings.HealthTextFontSize = "Размер шрифта здоровья"
L.Settings.HealthTextAnchor = "Привязка здоровья"
L.Settings.HealthTextOffsetX = "Смещение здоровья вправо"
L.Settings.HealthTextOffsetY = "Смещение здоровья вверх"
L.Settings.ResetHealthText = "Сбросить настройки здоровья"
L.Settings.PreviewHeading = "Предпросмотр"
L.Settings.PreviewCaption = "%d × %d · показано в масштабе %d%%"
L.Settings.Orientation = "Направление заполнения"
L.Settings.Horizontal = "Вдоль, затем вниз"
L.Settings.Vertical = "Вниз, затем вдоль"
L.Settings.Stride = "Переносить каждые"
L.Settings.GrowX = "Расти по горизонтали"
L.Settings.GrowRight = "Вправо"
L.Settings.GrowLeft = "Влево"
L.Settings.GrowY = "Расти по вертикали"
L.Settings.GrowDown = "Вниз"
L.Settings.GrowUp = "Вверх"
L.Settings.SpacingX = "Горизонтальный интервал"
L.Settings.SpacingY = "Вертикальный интервал"

L.Settings.FillHeading = "Заполнение"
L.Settings.Spacing = "Интервал"
L.Settings.SpacingHorizontalShort = "H"
L.Settings.SpacingVerticalShort = "V"
L.Settings.FillOrderHeading = "Порядок заполнения"
L.Settings.FillOrderCaption = "%s · перенос каждые %d · растёт %s, %s"
L.Settings.AllowGaps = "Отображать пустые ячейки"
L.Settings.AllowGapsHelp =
"Включено: игрок, покинувший рейд, оставляет свою ячейку пустой, и ничего больше не сдвигается. Выключено: оставшиеся выделения закроют промежуток, как только вы выйдете из боя."
L.Settings.ClearOnLeave = "Очищать состав при выходе из группы"
L.Settings.ClearOnLeaveHelp =
"Выключено: ваши выделения запоминаются между рейдами. Включено: выход из рейда полностью очищает сетку — каждого игрока и каждый разделитель — так что следующий начинается с нуля. Выход из игры, перезагрузка и переподключение не считаются выходом."
L.Settings.CombatHelp =
"Выделения перестраиваются только вне боя. Добавление или удаление во время боя запоминается и применяется в момент окончания боя; ничего не теряется, но сетка не изменится посреди боя."
L.Settings.RosterHelp =
"Вы можете перетаскивать игроков в группу ниже и из неё. Также можно перетащить их на контейнер Spotlights, если там уже есть хотя бы один другой игрок."
L.Settings.SlotsHeader = "Настроенные слоты"
L.Settings.RaidHeader = "Участники рейда"
L.Settings.AddSpacer = "Добавить разделитель"
L.Settings.NoSlots =
"Пока никто не выделен. Добавьте участника рейда из списка рядом или перетащите его сюда."
L.Settings.ClearSlots = "Очистить все слоты"
L.Settings.ClearSlotsPrompt =
"Удалить все настроенные слоты? Игроки и разделители удаляются вместе, и сетка начнётся с нуля."
L.Settings.ClearSlotsConfirm = "Очистить"
L.Settings.BlankSlot = "(разделитель)"
L.Settings.UnknownSlot = "(пусто)"
L.Settings.NotInRaid = "не в рейде"
L.Settings.AllSpotlighted = "все выделены"
L.Settings.UpShort = "^"
L.Settings.DownShort = "v"
L.Settings.RemoveShort = "x"
L.Settings.PlusShort = "+"
L.Settings.PresetsHeading = "Шаблоны"
L.Settings.PresetsCount = "Сохранено: %d"
L.Settings.PresetsNone =
"Пока нет сохранённых шаблонов. Сохраните настроенные места, чтобы создать первый."
L.Settings.PresetSave = "Сохранить"
L.Settings.PresetDelete = "Удалить"
L.Settings.PresetSavePrompt = "Название шаблона:"
L.Settings.PresetOverwritePrompt = "Шаблон «%s» уже существует. Заменить его?"
L.Settings.PresetOverwriteConfirm = "Заменить"
L.Settings.PresetDeletePrompt =
"Удалить шаблон «%s»? Настроенные места останутся без изменений."
L.Settings.PresetImportAdd = "Добавить шаблон"
L.Settings.PresetImportErrorPrefix = "строка не является шаблоном Spotlights"
L.Settings.PresetImportErrorPayload = "декодированные данные не являются списком мест"
L.Settings.AurasEvokerOnly = "Отслеживание аур — функция только для Эвокеров: Чувство силы и Предвидение."
L.Settings.Prescience = "Предвидение"
L.Settings.ShiftingSands = "Изменчивые пески"
L.Settings.Cooldowns = "Перезарядки и свои ауры"
L.Settings.Defensives = "Защита"
L.Settings.AuraAugmentationOnly = "Предвидение и Чувство силы доступны только Эвокерам специализации Усиление."
L.Settings.AuraTracked = "Отслеживание"
L.Settings.AuraFeatureToggle = "Отслеживать %s"
L.Settings.SensePower = "Чувство силы"
L.Settings.AuraBar = "Полоса состояния"
L.Settings.AuraIcon = "Значок"
L.Settings.AuraSquare = "Квадрат"
L.Settings.AuraSquareSize = "Размер"
L.Settings.AuraSquareColor = "Цвет блока"
L.Settings.AuraEnabled = "Показывать"
L.Settings.AuraColor = "Цвет полосы"
L.Settings.AuraAlpha = "Непрозрачность"
L.Settings.AuraWidth = "Ширина"
L.Settings.AuraHeight = "Высота"
L.Settings.AuraAnchor = "Привязать к"
L.Settings.AuraOffsetX = "Смещение вправо"
L.Settings.AuraOffsetY = "Смещение вверх"
L.Settings.AuraShowIcon = "Встроенный значок"
L.Settings.AuraIconSide = "Сторона значка"
L.Settings.AuraIconLeft = "Слева от полосы"
L.Settings.AuraGap = "Интервал"
L.Settings.AuraIconRight = "Справа от полосы"
L.Settings.AuraIconWidth = "Ширина"
L.Settings.AuraIconHeight = "Высота"
L.Settings.AuraShowSwipe = "Развёртка перезарядки"
L.Settings.AuraShowText = "Текст длительности"
L.Settings.AuraFont = "Шрифт длительности"
L.Settings.AuraFontSize = "Размер длительности"
L.Settings.AuraBorder = "Рамка"
L.Settings.AuraBorderStyle = "Стиль рамки"
L.Settings.AuraBorderSize = "Толщина рамки"
L.Settings.AuraBorderColor = "Цвет рамки"

L.Settings.AuraSummary = "%d × %d · %s · %s · %s"
L.Settings.AuraSummaryHidden = "Скрыто"
L.Settings.AuraSummarySwipeOn = "с разверткой"
L.Settings.AuraSummarySwipeOff = "без развертки"
L.Settings.AuraSummaryInlineIcon = "со значком"
L.Settings.AuraSummaryNoInlineIcon = "без значка"
L.Settings.AuraSummaryBorder = "рамка %d px"
L.Settings.AuraSummaryNoBorder = "без рамки"
L.Settings.AuraReset = "Сбросить по умолчанию"
L.Settings.AuraResetConfirm = "Сбросить"
L.Settings.AuraResetPrompt = "Сбросить полосу состояния и значок %s к настройкам по умолчанию?"
L.Settings.AuraResetDisplayPrompt = "Сбросить «%s» для %s к настройкам по умолчанию?"
L.Settings.AuraResetSpellsPrompt =
"Сбросить отслеживаемые для %s заклинания к выбору по умолчанию? Добавленные вами заклинания сохранятся."
L.Settings.AuraGroupCount = "%d/%d"
L.Settings.AuraEnableAll = "Включить все"
L.Settings.AuraDisableAll = "Отключить все"
L.Settings.AuraSpellMeta = "%d · %s"
L.Settings.AuraNoTrackedSpells = "%s отслеживает один конкретный эффект, поэтому выбирать здесь нечего."
L.Settings.AuraNoSpellMatches = "Нет заклинаний, соответствующих запросу."
L.Settings.AurasRebuildHelp =
"Некоторым настройкам может потребоваться перезагрузка после применения. Вам предложат сделать это, когда вы закончите настройку."
L.Settings.AuraBuiltinCooldowns = "Отслеживаемые перезарядки"
L.Settings.AuraBuiltinCooldownsNote =
"Отображение Чувства силы также показывает эти основные перезарядки, когда выделенный игрок использует одну из них."
L.Settings.AuraBuiltinDefensives = "Отслеживаемые защитные способности"
L.Settings.AuraBuiltinDefensivesNote =
"Показывать эти защитные способности, когда выделенный игрок использует одну из них."
L.Settings.AuraCustomCooldowns = "Свои ауры"
L.Settings.AuraCustomCooldownsNote =
"Это должны быть УСИЛЕНИЯ, появляющиеся на игроках, чтобы работали эффекты аксессуаров. Ослабления и произнесения здесь отслеживать нельзя, и добавление такого не даст никакого эффекта."
L.Settings.AuraCustomDefensivesNote =
"Добавьте ID защитных заклинаний, которых нет в поставляемом списке."
L.Settings.AuraCustomAdd = "Добавить"
L.Settings.AuraCustomSpellID = "ID заклинания"
L.Settings.ReloadPrompt =
"Некоторые настройки аур заменили свои отображения, а не изменили их, и оригиналы остаются в памяти, пока вы не перезагрузите.\n\nПерезагрузить сейчас?"
L.Settings.ReloadNow = "Перезагрузить"
L.Settings.ReloadLater = "Позже"
L.Settings.ImportReloadPrompt = "Настройки Spotlights импортированы. Перезагрузить интерфейс сейчас?"

L.Settings.Anchors.TOPLEFT = "Сверху слева"
L.Settings.Anchors.TOP = "Сверху"
L.Settings.Anchors.TOPRIGHT = "Сверху справа"
L.Settings.Anchors.LEFT = "Слева"
L.Settings.Anchors.CENTER = "По центру"
L.Settings.Anchors.RIGHT = "Справа"
L.Settings.Anchors.BOTTOMLEFT = "Снизу слева"
L.Settings.Anchors.BOTTOM = "Снизу"
L.Settings.Anchors.BOTTOMRIGHT = "Снизу справа"

L.Auras.SensePowerMissing =
"Spotlights не может определить, активно ли Чувство силы, если оно не находится на одной из ваших панелей команд.\n\nМогут отслеживаться только включённые вами перезарядки, что исключает некоторые призывы. Для полного отслеживания Чувство силы должно быть активно, поэтому поместите его на панель, если хотите включить."
L.Auras.SensePowerInactive =
"Чувство силы не активно.\n\nМогут отслеживаться только включённые вами перезарядки, что исключает некоторые призывы. Для полного отслеживания активируйте Чувство силы."

L.ContextMenu.Title = "Spotlights"
L.ContextMenu.Add = "Выделить этого игрока"
L.ContextMenu.Remove = "Прекратить выделение"

L.DragAssign.HintDrag = "Перетащите %s на выделение"
L.DragAssign.HintAdd = "Добавить %s как слот %d"
L.DragAssign.HintAppend = "Добавить %s в конец"
L.DragAssign.HintAlready = "%s уже занимает слот %d"
L.DragAssign.HintReorder = "Перетащите %s в ячейку для перестановки или к участникам рейда для удаления"
L.DragAssign.HintMove = "Переместить %s в слот %d"
L.DragAssign.HintRemove = "Удалить %s"

L.Preview.Label = "Выделение %d"

L.Mover.Label = "Spotlights"
L.Mover.Unlocked = "сетка разблокирована — перетащите её куда угодно, /spotlights mover для блокировки"
L.Mover.Locked = "сетка заблокирована"
L.Mover.LockedByCombat = "сетка заблокирована: вход в бой"
L.Mover.CombatRefused = "нельзя двигать сетку в бою"
L.Mover.Reset = "сетка возвращена в центр экрана"
